export const FETCH_TODOS = 'FETCH_TODOS'
export const LOADING = 'LOADING_TODOS'
export const ERROR = 'ERROR_TODOS'
export const UPDATE_INPUTS = 'UPDATE_INPUTS'
export const ADD_TODO = 'ADD_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
