export const FETCH_POSTS = 'FETCH_POSTS'
export const LOADING = 'POSTS_LOADING'
export const ERROR = 'POSTS_ERROR'
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS'
export const COM_LOADING = 'COM_LOADING'
export const COM_ERROR = 'COM_ERROR'
